// Code generated by the Lingua Franca compiler from:
// file://home/dobbs/ucb_related/fall2023/eecs149/port/src/RobotLineDetection.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/dobbs/ucb_related/fall2023/eecs149/port/src-gen/RobotLineDetection"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void _lf_set_default_command_line_options() {}
#include "_line.h"
#include "_display.h"
#include "_robotlinedetection_main.h"
typedef enum {
    robotlinedetection_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[robotlinedetection_main],robotlinedetection_main,_lf_number_of_workers,3,2,0,0,7,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _robotlinedetection_main_main_self_t* robotlinedetection_main_self[1];
    SUPPRESS_UNUSED_WARNING(robotlinedetection_main_self);
    _line_self_t* robotlinedetection_line_self[1];
    SUPPRESS_UNUSED_WARNING(robotlinedetection_line_self);
    _display_self_t* robotlinedetection_disp_self[1];
    SUPPRESS_UNUSED_WARNING(robotlinedetection_disp_self);
    // ***** Start initializing RobotLineDetection of class RobotLineDetection
    robotlinedetection_main_self[0] = new__robotlinedetection_main();
    robotlinedetection_main_self[0]->base.environment = &envs[robotlinedetection_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    robotlinedetection_main_self[0]->calibration_time = SEC(10);
    robotlinedetection_main_self[0]->sample_period = MSEC(100);
    envs[robotlinedetection_main].startup_reactions[startup_reaction_count[robotlinedetection_main]++] = &robotlinedetection_main_self[0]->_lf__reaction_0;
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    { // For scoping
        static int _initial = 0;
        robotlinedetection_main_self[0]->count = _initial;
    } // End scoping.
    // Initiaizing timer RobotLineDetection.t.
    robotlinedetection_main_self[0]->_lf__t.offset = 0;
    robotlinedetection_main_self[0]->_lf__t.period = MSEC(100);
    // Associate timer with the environment of its parent
    envs[robotlinedetection_main].timer_triggers[timer_triggers_count[robotlinedetection_main]++] = &robotlinedetection_main_self[0]->_lf__t;
    robotlinedetection_main_self[0]->_lf__t.mode = NULL;
    // Initiaizing timer RobotLineDetection.seconds.
    robotlinedetection_main_self[0]->_lf__seconds.offset = 0;
    robotlinedetection_main_self[0]->_lf__seconds.period = SEC(1);
    // Associate timer with the environment of its parent
    envs[robotlinedetection_main].timer_triggers[timer_triggers_count[robotlinedetection_main]++] = &robotlinedetection_main_self[0]->_lf__seconds;
    robotlinedetection_main_self[0]->_lf__seconds.mode = NULL;
    // Initiaizing timer RobotLineDetection.end_calibration.
    robotlinedetection_main_self[0]->_lf__end_calibration.offset = SEC(10);
    robotlinedetection_main_self[0]->_lf__end_calibration.period = 0;
    // Associate timer with the environment of its parent
    envs[robotlinedetection_main].timer_triggers[timer_triggers_count[robotlinedetection_main]++] = &robotlinedetection_main_self[0]->_lf__end_calibration;
    robotlinedetection_main_self[0]->_lf__end_calibration.mode = NULL;
    
    robotlinedetection_main_self[0]->_lf__reaction_0.deadline = NEVER;
    robotlinedetection_main_self[0]->_lf__reaction_1.deadline = NEVER;
    robotlinedetection_main_self[0]->_lf__reaction_2.deadline = NEVER;
    robotlinedetection_main_self[0]->_lf__reaction_3.deadline = NEVER;
    robotlinedetection_main_self[0]->_lf__reaction_4.deadline = NEVER;
    {
        // ***** Start initializing RobotLineDetection.line of class Line
        robotlinedetection_line_self[0] = new__line();
        robotlinedetection_line_self[0]->base.environment = &envs[robotlinedetection_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        robotlinedetection_line_self[0]->_lf_reflect_width = -2;
        // width of -2 indicates that it is not a multiport.
        robotlinedetection_line_self[0]->_lf_calibrate_width = -2;
        // width of -2 indicates that it is not a multiport.
        robotlinedetection_line_self[0]->_lf_trigger_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        { // For scoping
            static bool _initial = true;
            robotlinedetection_line_self[0]->calibrating = _initial;
        } // End scoping.
        { // For scoping
            static bool _initial = false;
            robotlinedetection_line_self[0]->calibrated = _initial;
        } // End scoping.
    
        robotlinedetection_line_self[0]->_lf__reaction_0.deadline = NEVER;
        robotlinedetection_line_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing RobotLineDetection.line
    }
    {
        // ***** Start initializing RobotLineDetection.disp of class Display
        robotlinedetection_disp_self[0] = new__display();
        robotlinedetection_disp_self[0]->base.environment = &envs[robotlinedetection_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        robotlinedetection_disp_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        robotlinedetection_disp_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        robotlinedetection_disp_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        robotlinedetection_disp_self[0]->_lf_line3_width = -2;
        envs[robotlinedetection_main].startup_reactions[startup_reaction_count[robotlinedetection_main]++] = &robotlinedetection_disp_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        robotlinedetection_disp_self[0]->_lf__reaction_0.deadline = NEVER;
        robotlinedetection_disp_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing RobotLineDetection.disp
    }
    //***** End initializing RobotLineDetection
    // **** Start deferred initialize for RobotLineDetection
    {
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of RobotLineDetection.
        robotlinedetection_main_self[0]->_lf__reaction_0.num_outputs = 3;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        robotlinedetection_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                3, sizeof(trigger_t**),
                &robotlinedetection_main_self[0]->base.allocations);
        robotlinedetection_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                3, sizeof(int),
                &robotlinedetection_main_self[0]->base.allocations);
        robotlinedetection_main_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                3, sizeof(bool*),
                &robotlinedetection_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                robotlinedetection_main_self[0]->_lf__reaction_0.output_produced[count++] = &robotlinedetection_main_self[0]->_lf_disp.line0.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                robotlinedetection_main_self[0]->_lf__reaction_0.output_produced[count++] = &robotlinedetection_main_self[0]->_lf_disp.line1.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                robotlinedetection_main_self[0]->_lf__reaction_0.output_produced[count++] = &robotlinedetection_main_self[0]->_lf_disp.line2.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of RobotLineDetection
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of RobotLineDetection.
        robotlinedetection_main_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        robotlinedetection_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &robotlinedetection_main_self[0]->base.allocations);
        robotlinedetection_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &robotlinedetection_main_self[0]->base.allocations);
        robotlinedetection_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &robotlinedetection_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                robotlinedetection_main_self[0]->_lf__reaction_1.output_produced[count++] = &robotlinedetection_main_self[0]->_lf_disp.line3.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of RobotLineDetection
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of RobotLineDetection.
        robotlinedetection_main_self[0]->_lf__reaction_2.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        robotlinedetection_main_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &robotlinedetection_main_self[0]->base.allocations);
        robotlinedetection_main_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &robotlinedetection_main_self[0]->base.allocations);
        robotlinedetection_main_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &robotlinedetection_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                robotlinedetection_main_self[0]->_lf__reaction_2.output_produced[count++] = &robotlinedetection_main_self[0]->_lf_line.calibrate.is_present;
            }
        }
        
        // ** End initialization for reaction 2 of RobotLineDetection
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_3 of RobotLineDetection.
        robotlinedetection_main_self[0]->_lf__reaction_3.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        robotlinedetection_main_self[0]->_lf__reaction_3.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &robotlinedetection_main_self[0]->base.allocations);
        robotlinedetection_main_self[0]->_lf__reaction_3.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &robotlinedetection_main_self[0]->base.allocations);
        robotlinedetection_main_self[0]->_lf__reaction_3.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &robotlinedetection_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                robotlinedetection_main_self[0]->_lf__reaction_3.output_produced[count++] = &robotlinedetection_main_self[0]->_lf_line.trigger.is_present;
            }
        }
        
        // ** End initialization for reaction 3 of RobotLineDetection
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_4 of RobotLineDetection.
        robotlinedetection_main_self[0]->_lf__reaction_4.num_outputs = 3;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        robotlinedetection_main_self[0]->_lf__reaction_4.triggers = (trigger_t***)_lf_allocate(
                3, sizeof(trigger_t**),
                &robotlinedetection_main_self[0]->base.allocations);
        robotlinedetection_main_self[0]->_lf__reaction_4.triggered_sizes = (int*)_lf_allocate(
                3, sizeof(int),
                &robotlinedetection_main_self[0]->base.allocations);
        robotlinedetection_main_self[0]->_lf__reaction_4.output_produced = (bool**)_lf_allocate(
                3, sizeof(bool*),
                &robotlinedetection_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                robotlinedetection_main_self[0]->_lf__reaction_4.output_produced[count++] = &robotlinedetection_main_self[0]->_lf_disp.line0.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                robotlinedetection_main_self[0]->_lf__reaction_4.output_produced[count++] = &robotlinedetection_main_self[0]->_lf_disp.line1.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                robotlinedetection_main_self[0]->_lf__reaction_4.output_produced[count++] = &robotlinedetection_main_self[0]->_lf_disp.line2.is_present;
            }
        }
        
        // ** End initialization for reaction 4 of RobotLineDetection
    
        // **** Start deferred initialize for RobotLineDetection.line
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of RobotLineDetection.line.
            robotlinedetection_line_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of RobotLineDetection.line
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of RobotLineDetection.line.
            robotlinedetection_line_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            robotlinedetection_line_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &robotlinedetection_line_self[0]->base.allocations);
            robotlinedetection_line_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &robotlinedetection_line_self[0]->base.allocations);
            robotlinedetection_line_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &robotlinedetection_line_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    robotlinedetection_line_self[0]->_lf__reaction_1.output_produced[count++] = &robotlinedetection_line_self[0]->_lf_reflect.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of RobotLineDetection.line
        
        }
        // **** End of deferred initialize for RobotLineDetection.line
        // **** Start deferred initialize for RobotLineDetection.disp
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of RobotLineDetection.disp.
            robotlinedetection_disp_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of RobotLineDetection.disp
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of RobotLineDetection.disp.
            robotlinedetection_disp_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of RobotLineDetection.disp
        
        }
        // **** End of deferred initialize for RobotLineDetection.disp
    }
    // **** End of deferred initialize for RobotLineDetection
    // **** Start non-nested deferred initialize for RobotLineDetection
    {
        // Set number of destination reactors for port disp.line0.
        // Iterate over range RobotLineDetection.disp.line0(0,1)->[RobotLineDetection.disp.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_main_self[src_runtime]->_lf_disp.line0._base.num_destinations = 1;
            robotlinedetection_main_self[src_runtime]->_lf_disp.line0._base.source_reactor = (self_base_t*)robotlinedetection_main_self[src_runtime];
        }
        // Set number of destination reactors for port disp.line1.
        // Iterate over range RobotLineDetection.disp.line1(0,1)->[RobotLineDetection.disp.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_main_self[src_runtime]->_lf_disp.line1._base.num_destinations = 1;
            robotlinedetection_main_self[src_runtime]->_lf_disp.line1._base.source_reactor = (self_base_t*)robotlinedetection_main_self[src_runtime];
        }
        // Set number of destination reactors for port disp.line2.
        // Iterate over range RobotLineDetection.disp.line2(0,1)->[RobotLineDetection.disp.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_main_self[src_runtime]->_lf_disp.line2._base.num_destinations = 1;
            robotlinedetection_main_self[src_runtime]->_lf_disp.line2._base.source_reactor = (self_base_t*)robotlinedetection_main_self[src_runtime];
        }
        // Set number of destination reactors for port disp.line3.
        // Iterate over range RobotLineDetection.disp.line3(0,1)->[RobotLineDetection.disp.line3(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_main_self[src_runtime]->_lf_disp.line3._base.num_destinations = 1;
            robotlinedetection_main_self[src_runtime]->_lf_disp.line3._base.source_reactor = (self_base_t*)robotlinedetection_main_self[src_runtime];
        }
        // Set number of destination reactors for port line.calibrate.
        // Iterate over range RobotLineDetection.line.calibrate(0,1)->[RobotLineDetection.line.calibrate(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_main_self[src_runtime]->_lf_line.calibrate._base.num_destinations = 1;
            robotlinedetection_main_self[src_runtime]->_lf_line.calibrate._base.source_reactor = (self_base_t*)robotlinedetection_main_self[src_runtime];
        }
        // Set number of destination reactors for port line.trigger.
        // Iterate over range RobotLineDetection.line.trigger(0,1)->[RobotLineDetection.line.trigger(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_main_self[src_runtime]->_lf_line.trigger._base.num_destinations = 1;
            robotlinedetection_main_self[src_runtime]->_lf_line.trigger._base.source_reactor = (self_base_t*)robotlinedetection_main_self[src_runtime];
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range RobotLineDetection.disp.line0(0,1)->[RobotLineDetection.disp.line0(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 0 of RobotLineDetection triggers 1 downstream reactions
                // through port RobotLineDetection.disp.line0.
                robotlinedetection_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of RobotLineDetection, allocate an
                // array of trigger pointers for downstream reactions through port RobotLineDetection.disp.line0
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &robotlinedetection_main_self[src_runtime]->base.allocations); 
                robotlinedetection_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range RobotLineDetection.disp.line1(0,1)->[RobotLineDetection.disp.line1(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 0 of RobotLineDetection triggers 1 downstream reactions
                // through port RobotLineDetection.disp.line1.
                robotlinedetection_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of RobotLineDetection, allocate an
                // array of trigger pointers for downstream reactions through port RobotLineDetection.disp.line1
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &robotlinedetection_main_self[src_runtime]->base.allocations); 
                robotlinedetection_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range RobotLineDetection.disp.line2(0,1)->[RobotLineDetection.disp.line2(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 0 of RobotLineDetection triggers 1 downstream reactions
                // through port RobotLineDetection.disp.line2.
                robotlinedetection_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of RobotLineDetection, allocate an
                // array of trigger pointers for downstream reactions through port RobotLineDetection.disp.line2
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &robotlinedetection_main_self[src_runtime]->base.allocations); 
                robotlinedetection_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges RobotLineDetection.disp.line0(0,1)->[RobotLineDetection.disp.line0(0,1)] and RobotLineDetection.disp.line0(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range RobotLineDetection.disp.line0(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port RobotLineDetection.disp.line0's trigger struct.
                    robotlinedetection_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &robotlinedetection_disp_self[dst_runtime]->_lf__line0;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 1;
            // Iterate over ranges RobotLineDetection.disp.line1(0,1)->[RobotLineDetection.disp.line1(0,1)] and RobotLineDetection.disp.line1(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range RobotLineDetection.disp.line1(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port RobotLineDetection.disp.line1's trigger struct.
                    robotlinedetection_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &robotlinedetection_disp_self[dst_runtime]->_lf__line1;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 2;
            // Iterate over ranges RobotLineDetection.disp.line2(0,1)->[RobotLineDetection.disp.line2(0,1)] and RobotLineDetection.disp.line2(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range RobotLineDetection.disp.line2(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port RobotLineDetection.disp.line2's trigger struct.
                    robotlinedetection_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &robotlinedetection_disp_self[dst_runtime]->_lf__line2;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range RobotLineDetection.disp.line3(0,1)->[RobotLineDetection.disp.line3(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 1 of RobotLineDetection triggers 1 downstream reactions
                // through port RobotLineDetection.disp.line3.
                robotlinedetection_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of RobotLineDetection, allocate an
                // array of trigger pointers for downstream reactions through port RobotLineDetection.disp.line3
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &robotlinedetection_main_self[src_runtime]->base.allocations); 
                robotlinedetection_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges RobotLineDetection.disp.line3(0,1)->[RobotLineDetection.disp.line3(0,1)] and RobotLineDetection.disp.line3(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range RobotLineDetection.disp.line3(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port RobotLineDetection.disp.line3's trigger struct.
                    robotlinedetection_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &robotlinedetection_disp_self[dst_runtime]->_lf__line3;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range RobotLineDetection.line.calibrate(0,1)->[RobotLineDetection.line.calibrate(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 2 of RobotLineDetection triggers 1 downstream reactions
                // through port RobotLineDetection.line.calibrate.
                robotlinedetection_main_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 2 of RobotLineDetection, allocate an
                // array of trigger pointers for downstream reactions through port RobotLineDetection.line.calibrate
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &robotlinedetection_main_self[src_runtime]->base.allocations); 
                robotlinedetection_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges RobotLineDetection.line.calibrate(0,1)->[RobotLineDetection.line.calibrate(0,1)] and RobotLineDetection.line.calibrate(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range RobotLineDetection.line.calibrate(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port RobotLineDetection.line.calibrate's trigger struct.
                    robotlinedetection_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &robotlinedetection_line_self[dst_runtime]->_lf__calibrate;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range RobotLineDetection.line.trigger(0,1)->[RobotLineDetection.line.trigger(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 3 of RobotLineDetection triggers 1 downstream reactions
                // through port RobotLineDetection.line.trigger.
                robotlinedetection_main_self[src_runtime]->_lf__reaction_3.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 3 of RobotLineDetection, allocate an
                // array of trigger pointers for downstream reactions through port RobotLineDetection.line.trigger
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &robotlinedetection_main_self[src_runtime]->base.allocations); 
                robotlinedetection_main_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges RobotLineDetection.line.trigger(0,1)->[RobotLineDetection.line.trigger(0,1)] and RobotLineDetection.line.trigger(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range RobotLineDetection.line.trigger(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port RobotLineDetection.line.trigger's trigger struct.
                    robotlinedetection_main_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime] + src_channel][0] = &robotlinedetection_line_self[dst_runtime]->_lf__trigger;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range RobotLineDetection.disp.line0(0,1)->[RobotLineDetection.disp.line0(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 4 of RobotLineDetection triggers 1 downstream reactions
                // through port RobotLineDetection.disp.line0.
                robotlinedetection_main_self[src_runtime]->_lf__reaction_4.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 4 of RobotLineDetection, allocate an
                // array of trigger pointers for downstream reactions through port RobotLineDetection.disp.line0
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &robotlinedetection_main_self[src_runtime]->base.allocations); 
                robotlinedetection_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range RobotLineDetection.disp.line1(0,1)->[RobotLineDetection.disp.line1(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 4 of RobotLineDetection triggers 1 downstream reactions
                // through port RobotLineDetection.disp.line1.
                robotlinedetection_main_self[src_runtime]->_lf__reaction_4.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 4 of RobotLineDetection, allocate an
                // array of trigger pointers for downstream reactions through port RobotLineDetection.disp.line1
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &robotlinedetection_main_self[src_runtime]->base.allocations); 
                robotlinedetection_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range RobotLineDetection.disp.line2(0,1)->[RobotLineDetection.disp.line2(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 4 of RobotLineDetection triggers 1 downstream reactions
                // through port RobotLineDetection.disp.line2.
                robotlinedetection_main_self[src_runtime]->_lf__reaction_4.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 4 of RobotLineDetection, allocate an
                // array of trigger pointers for downstream reactions through port RobotLineDetection.disp.line2
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &robotlinedetection_main_self[src_runtime]->base.allocations); 
                robotlinedetection_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges RobotLineDetection.disp.line0(0,1)->[RobotLineDetection.disp.line0(0,1)] and RobotLineDetection.disp.line0(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range RobotLineDetection.disp.line0(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port RobotLineDetection.disp.line0's trigger struct.
                    robotlinedetection_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime] + src_channel][0] = &robotlinedetection_disp_self[dst_runtime]->_lf__line0;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 1;
            // Iterate over ranges RobotLineDetection.disp.line1(0,1)->[RobotLineDetection.disp.line1(0,1)] and RobotLineDetection.disp.line1(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range RobotLineDetection.disp.line1(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port RobotLineDetection.disp.line1's trigger struct.
                    robotlinedetection_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime] + src_channel][0] = &robotlinedetection_disp_self[dst_runtime]->_lf__line1;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 2;
            // Iterate over ranges RobotLineDetection.disp.line2(0,1)->[RobotLineDetection.disp.line2(0,1)] and RobotLineDetection.disp.line2(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range RobotLineDetection.disp.line2(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port RobotLineDetection.disp.line2's trigger struct.
                    robotlinedetection_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime] + src_channel][0] = &robotlinedetection_disp_self[dst_runtime]->_lf__line2;
                }
            }
        }
    
        // **** Start non-nested deferred initialize for RobotLineDetection.line
        {
        
            // For reference counting, set num_destinations for port RobotLineDetection.line.reflect.
            // Iterate over range RobotLineDetection.line.reflect(0,1)->[RobotLineDetection.line.reflect(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                robotlinedetection_line_self[src_runtime]->_lf_reflect._base.num_destinations = 1;
                robotlinedetection_line_self[src_runtime]->_lf_reflect._base.source_reactor = (self_base_t*)robotlinedetection_line_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range RobotLineDetection.line.reflect(0,1)->[RobotLineDetection.line.reflect(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of RobotLineDetection.line triggers 1 downstream reactions
                    // through port RobotLineDetection.line.reflect.
                    robotlinedetection_line_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of RobotLineDetection.line, allocate an
                    // array of trigger pointers for downstream reactions through port RobotLineDetection.line.reflect
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &robotlinedetection_line_self[src_runtime]->base.allocations); 
                    robotlinedetection_line_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges RobotLineDetection.line.reflect(0,1)->[RobotLineDetection.line.reflect(0,1)] and RobotLineDetection.line.reflect(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range RobotLineDetection.line.reflect(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Port RobotLineDetection.line.reflect has reactions in its parent's parent.
                        // Point to the trigger struct for those reactions.
                        robotlinedetection_line_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &robotlinedetection_main_self[dst_runtime]->_lf_line.reflect_trigger;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for RobotLineDetection.line
        // **** Start non-nested deferred initialize for RobotLineDetection.disp
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for RobotLineDetection.disp
    }
    // **** End of non-nested deferred initialize for RobotLineDetection
    // Connect inputs and outputs for reactor RobotLineDetection.
    // Connect inputs and outputs for reactor RobotLineDetection.line.
    // Connect RobotLineDetection.line.calibrate(0,1)->[RobotLineDetection.line.calibrate(0,1)] to port RobotLineDetection.line.calibrate(0,1)
    // Iterate over ranges RobotLineDetection.line.calibrate(0,1)->[RobotLineDetection.line.calibrate(0,1)] and RobotLineDetection.line.calibrate(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotLineDetection.line.calibrate(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_line_self[dst_runtime]->_lf_calibrate = (_line_calibrate_t*)&robotlinedetection_main_self[src_runtime]->_lf_line.calibrate;
        }
    }
    // Connect RobotLineDetection.line.trigger(0,1)->[RobotLineDetection.line.trigger(0,1)] to port RobotLineDetection.line.trigger(0,1)
    // Iterate over ranges RobotLineDetection.line.trigger(0,1)->[RobotLineDetection.line.trigger(0,1)] and RobotLineDetection.line.trigger(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotLineDetection.line.trigger(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_line_self[dst_runtime]->_lf_trigger = (_line_trigger_t*)&robotlinedetection_main_self[src_runtime]->_lf_line.trigger;
        }
    }
    // Connect RobotLineDetection.line.reflect(0,1)->[RobotLineDetection.line.reflect(0,1)] to port RobotLineDetection.line.reflect(0,1)
    // Iterate over ranges RobotLineDetection.line.reflect(0,1)->[RobotLineDetection.line.reflect(0,1)] and RobotLineDetection.line.reflect(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotLineDetection.line.reflect(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_main_self[dst_runtime]->_lf_line.reflect = (_line_reflect_t*)&robotlinedetection_line_self[src_runtime]->_lf_reflect;
        }
    }
    // Connect inputs and outputs for reactor RobotLineDetection.disp.
    // Connect RobotLineDetection.disp.line0(0,1)->[RobotLineDetection.disp.line0(0,1)] to port RobotLineDetection.disp.line0(0,1)
    // Iterate over ranges RobotLineDetection.disp.line0(0,1)->[RobotLineDetection.disp.line0(0,1)] and RobotLineDetection.disp.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotLineDetection.disp.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_disp_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&robotlinedetection_main_self[src_runtime]->_lf_disp.line0;
        }
    }
    // Connect RobotLineDetection.disp.line1(0,1)->[RobotLineDetection.disp.line1(0,1)] to port RobotLineDetection.disp.line1(0,1)
    // Iterate over ranges RobotLineDetection.disp.line1(0,1)->[RobotLineDetection.disp.line1(0,1)] and RobotLineDetection.disp.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotLineDetection.disp.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_disp_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&robotlinedetection_main_self[src_runtime]->_lf_disp.line1;
        }
    }
    // Connect RobotLineDetection.disp.line2(0,1)->[RobotLineDetection.disp.line2(0,1)] to port RobotLineDetection.disp.line2(0,1)
    // Iterate over ranges RobotLineDetection.disp.line2(0,1)->[RobotLineDetection.disp.line2(0,1)] and RobotLineDetection.disp.line2(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotLineDetection.disp.line2(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_disp_self[dst_runtime]->_lf_line2 = (_display_line2_t*)&robotlinedetection_main_self[src_runtime]->_lf_disp.line2;
        }
    }
    // Connect RobotLineDetection.disp.line3(0,1)->[RobotLineDetection.disp.line3(0,1)] to port RobotLineDetection.disp.line3(0,1)
    // Iterate over ranges RobotLineDetection.disp.line3(0,1)->[RobotLineDetection.disp.line3(0,1)] and RobotLineDetection.disp.line3(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotLineDetection.disp.line3(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robotlinedetection_disp_self[dst_runtime]->_lf_line3 = (_display_line3_t*)&robotlinedetection_main_self[src_runtime]->_lf_disp.line3;
        }
    }
    {
    }
    {
    }
    // Add port RobotLineDetection.disp.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[robotlinedetection_main].is_present_fields[0 + count] = &robotlinedetection_main_self[0]->_lf_disp.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[robotlinedetection_main]._lf_intended_tag_fields[0 + count] = &robotlinedetection_main_self[0]->_lf_disp.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port RobotLineDetection.disp.line1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[robotlinedetection_main].is_present_fields[1 + count] = &robotlinedetection_main_self[0]->_lf_disp.line1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[robotlinedetection_main]._lf_intended_tag_fields[1 + count] = &robotlinedetection_main_self[0]->_lf_disp.line1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port RobotLineDetection.disp.line2 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[robotlinedetection_main].is_present_fields[2 + count] = &robotlinedetection_main_self[0]->_lf_disp.line2.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[robotlinedetection_main]._lf_intended_tag_fields[2 + count] = &robotlinedetection_main_self[0]->_lf_disp.line2.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port RobotLineDetection.disp.line3 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[robotlinedetection_main].is_present_fields[3 + count] = &robotlinedetection_main_self[0]->_lf_disp.line3.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[robotlinedetection_main]._lf_intended_tag_fields[3 + count] = &robotlinedetection_main_self[0]->_lf_disp.line3.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port RobotLineDetection.line.calibrate to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[robotlinedetection_main].is_present_fields[4 + count] = &robotlinedetection_main_self[0]->_lf_line.calibrate.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[robotlinedetection_main]._lf_intended_tag_fields[4 + count] = &robotlinedetection_main_self[0]->_lf_line.calibrate.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port RobotLineDetection.line.trigger to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[robotlinedetection_main].is_present_fields[5 + count] = &robotlinedetection_main_self[0]->_lf_line.trigger.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[robotlinedetection_main]._lf_intended_tag_fields[5 + count] = &robotlinedetection_main_self[0]->_lf_line.trigger.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port RobotLineDetection.line.reflect to array of is_present fields.
            envs[robotlinedetection_main].is_present_fields[6 + count] = &robotlinedetection_line_self[0]->_lf_reflect.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port RobotLineDetection.line.reflect to array of intended_tag fields.
            envs[robotlinedetection_main]._lf_intended_tag_fields[6 + count] = &robotlinedetection_line_self[0]->_lf_reflect.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance RobotLineDetection
    {
        robotlinedetection_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        robotlinedetection_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        robotlinedetection_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 1 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        robotlinedetection_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        robotlinedetection_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        robotlinedetection_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0002LL;
        robotlinedetection_main_self[0]->_lf__reaction_3.chain_id = 1;
        // index is the OR of level 3 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        robotlinedetection_main_self[0]->_lf__reaction_3.index = 0xffffffffffff0003LL;
        robotlinedetection_main_self[0]->_lf__reaction_4.chain_id = 1;
        // index is the OR of level 5 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        robotlinedetection_main_self[0]->_lf__reaction_4.index = 0xffffffffffff0005LL;
    
        // Set reaction priorities for ReactorInstance RobotLineDetection.line
        {
            robotlinedetection_line_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robotlinedetection_line_self[0]->_lf__reaction_0.index = 0xffffffffffff0003LL;
            robotlinedetection_line_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robotlinedetection_line_self[0]->_lf__reaction_1.index = 0xffffffffffff0004LL;
        }
    
    
        // Set reaction priorities for ReactorInstance RobotLineDetection.disp
        {
            robotlinedetection_disp_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robotlinedetection_disp_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            robotlinedetection_disp_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 6 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            robotlinedetection_disp_self[0]->_lf__reaction_1.index = 0xffffffffffff0006LL;
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
